### ISSUE TITLE
Logo image broken on search page

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#44]
On a few occasions now when I have been on the website and I have searched for a title using the ‘Search’ box a banner appears on the screen with a broken image icon and a purple bar in the middle (please see attached).

 

When this happens you can still move your mouse around the screen but when you go to click on a link the website auto clicks onto the purple banner and takes you back to the homepage.

 

I tested and this doesn’t happen in Explorer – only in Chrome.
![chrome browser web error](https://cloud.githubusercontent.com/assets/7650441/6889137/ea534ce2-d65d-11e4-9857-22c9d212ec2d.jpg)

**Comment by janetgatsby** [comment]
On Sun, Mar 29, 2015 at 9:05 PM, Patrick Burch <patthropus@gmail.com> wrote:

    Definitely a broken image link, I see it on dev all the time before I link all images from www.  I'll investigate after deployment tonight.

    On Sun, Mar 29, 2015 at 9:02 PM, Travis Larson <admin@travislarson.com> wrote:

        Looks like the logo image was broken on the screen shot. The purple is actually the logo h1 being made super-sized to hide by CSS, hence why it links to the homepage.

        I'm not able to reproduce it at that URL on Mac Chrome:
        http://fivemile.com.au/catalog/children/very-first-sounds-busy-duck

        My guess is bad cache on the image logo. Is it on more than one computer, and only after searching?

**Comment by patpluspun** [comment]
1 hour.

I fixed this directly on production after a brief QA on test.  The issue was the `$` in the file name, Chrome didn't decode it correctly.  I'm not sure why it didn't happen before, perhaps it was a Chrome update that fixed previously erroneous url encoding.

Anyways, the fix is to not use strange characters for file names.  I can insert a hook that will strip weird characters out if we want, but that will obviously take longer than renaming the file before upload.
